### PR TITLE
patched tbb

### PR DESCRIPTION
**Pull request by muellerbernd**
Hey. I had some trouble with tbb after the last updates, so I created a patch for this package. While compiling there can be some issues with tbb in the file _/usr/include/oneapi/tbb/profiling.h_ .Dirty fix: Follow the compiler and comment the lines out, which cause the problems.

### CODE REVIEW

**Comment by bartoszek** [comment]
Sorry, but it wont fly. Only honest patch for `tbb` no wonkery 😏

**Comment by bartoszek** [comment]
@muellerbernd I thought about pushing prev version on tbb to AUR in order for the `cloudcompare` build to be tbb enabled 🤔

**Comment by bartoszek** [comment]
Ok, finally got my shit together and bodge a honest patch for tbb:2021 :feelsgood: 
@muellerbernd You ware close lad, instead of removing colliding shit form `tbb/profile` one had to disable QT keywords:emit,signals,slots with `QT_NO_KEYWORDS` define and patch all they occurrences in `cloudcompare` source.
https://github.com/CloudCompare/CloudCompare/issues/1385

**Comment by muellerbernd** [comment]
@bartoszek it was my first pull request. I needed to use cloudcompare for a project and therefore I used the simple way and removed the colliding stuff from `tbb/profile`. nice that you were able to patch this :thumbsup:

**Pull request closed without merging**
