### PR TITLE
FEATURE: Re-activate plugins and fix compilation

### PR DESCRIPTION
**Pull request by oleid**
These changes restore many plug-ins and fix compilation of `pcl`.

### CODE REVIEW

**Comment by bartoszek** [comment]
Doesn't work without `makedepnds+=(tbb)` 😏 
http://ix.io/2GeE

**Comment by oleid** [comment]
> Doesn't work without `makedepnds+=(tbb)` smirk
> http://ix.io/2GeE

Oh, you're right, tbb is missing. It would seem, however, it is a runtime dependency according to `ldd`. I've added `tbb` to the dependencies and converted the remaining plugins, removed non-existing ones.

**Comment by bartoszek** [comment]
There's one last unused variable defined in cmake call.
```
  Manually-specified variables were not used by the project:

    OPTION_PDAL_LAS
```

**Comment by oleid** [comment]
> There's one last unused variable defined in cmake call.
> 
> ```
>   Manually-specified variables were not used by the project:
> 
>     OPTION_PDAL_LAS
> ```

You're right, it would seem that option was removed.
 
> btw. would you like to `co-maintain` this package? what's your AUR username?

I'm "leidola" on AUR. Currently, I'm evaluating different tools for working with point clouds. `cloudcompare` is a nice tool, however, I'm not sure, yet, if I'm going to use it (or any other). I'm working with radar based point clouds, so I might need something completely different. But I thought the least I could to is help a little with the package :)

**Pull request merged**
